name: converter
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  prompt_king: ^0.0.1
  image: ^3.0.2
dev_dependencies:
  pedantic: ^1.10.0
  